spring:
  application:
    name: api-gateway
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    
zuul:
  ignore-security-headers: false  routes:    shopservice:
      service-id: shop-service 
  
